# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(627, 440)
        self.create_yellow_circle_button = QtWidgets.QPushButton(Dialog)
        self.create_yellow_circle_button.setGeometry(QtCore.QRect(220, 320, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.create_yellow_circle_button.setFont(font)
        self.create_yellow_circle_button.setObjectName("create_yellow_circle_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.create_yellow_circle_button.setText(_translate("Dialog", "CREATE CIRCLE"))
